language: php

php:
  - 8.1

services:
  - mysql

addons:
  postgresql: "15.4"

before_script:
  - make test/postgres-scripts/create-database.sql
  - psql -U postgres -v ON_ERROR_STOP=1                <test/postgres-scripts/create-database.sql
  - psql -U postgres -v ON_ERROR_STOP=1 phpstoragetest <test/postgres-scripts/create-postgis-extension.sql
  - mysql --user=root --password='' < test/mysql-scripts/create-database.sql

script: make run-unit-tests
