language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

addons:
  postgresql: "9.3"

before_script:
  - make test/db-scripts/create-postgres-database.sql
  - psql -U postgres -v ON_ERROR_STOP=1                <test/db-scripts/create-postgres-database.sql
  - psql -U postgres -v ON_ERROR_STOP=1 phpstoragetest <test/db-scripts/create-postgis-extension.sql

script: make run-unit-tests
